[workspace]

members = [
    "day_1",
    "day_2",
    "day_3",
    "day_4",
    "day_5",
    "day_6",
    "day_7",
    "day_8",
]

[workspace.dependencies]
color-eyre = "0.6.2"
itertools = "0.11.0"
nom = "7.1.3"