[package]
name = "pipe_maze"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
queue = { path = "../queue" }
crossterm = "0.27.0"
ctrlc = "3.4.4"
ratatui = "0.27.0"

[dev-dependencies]
pretty_assertions.workspace = true
