pub fn part1(_input: &str) -> usize {
    todo!("Part 1 implementation");
}

pub fn part2(_input: &str) -> usize {
    todo!("Part 2 implementation");
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST: &str = ".......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............";

    #[test]
    fn test_part1() {
        assert_eq!(part1(TEST), 21);
    }

    #[test]
    fn test_part2() {
        todo!("Part 2 UT");
    }
}
